# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_shopcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('isselect', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.axf_goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.user')),
            ],
            options={
                'db_table': 'shopcar',
            },
        ),
        migrations.AlterField(
            model_name='axf_foodtypes',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='axf_foodtypes',
            name='typename',
            field=models.CharField(max_length=100),
        ),
    ]
