# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180821_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('upddate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='axf_order_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.axf_goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.axf_order')),
            ],
            options={
                'db_table': 'order_goods',
            },
        ),
    ]
